# Site settings

title: Project Pages
header-img: img/home-bg.jpg
email: yangzhen@ecust.edu.cn
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/project-page-test"
url: "http://doudon.github.io"
github_username:  doudon
project_repository: project-page-test
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
